services:
  redis:
    image: 'redis:alpine'
    volumes:
      - 'redis:/data'
    env_file:
      - ./project.env
    healthcheck:
      test: [ 'CMD', 'redis-cli', 'ping']
  sql:
    build:
      context: .
      dockerfile: ./sql/Dockerfile
    volumes:
      - capstone-sql:/var/lib/postgresql/data/
    env_file:
      - ./project.env
  backend:
    build: backend
    env_file:
      - ./project.env
    user: 'node'
    volumes:
      - ./backend/src:/home/node/app/src
      - ./backend/migrations:/home/node/app/migrations
      - ./backend/package.json:/home/node/app/package.json
volumes:
  capstone-sql:
    driver: local
  redis:
    driver: local